version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adm@adm.com
      PGADMIN_DEFAULT_PASSWORD: gdadim1425
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/rails/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    command: ./bin/rails server -b 0.0.0.0

  redis:
    image: redis:latest
    restart: always

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - db
      - redis
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/rails/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./wait-for-it.sh db:5432 -- bundle exec sidekiq

volumes:
  gem_cache:
  db-data:
  pgadmin-data:
  node_modules:
