require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/careers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Career. As you add validations to Career, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Career.create! valid_attributes
      get careers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      career = Career.create! valid_attributes
      get career_url(career)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_career_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      career = Career.create! valid_attributes
      get edit_career_url(career)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Career" do
        expect {
          post careers_url, params: { career: valid_attributes }
        }.to change(Career, :count).by(1)
      end

      it "redirects to the created career" do
        post careers_url, params: { career: valid_attributes }
        expect(response).to redirect_to(career_url(Career.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Career" do
        expect {
          post careers_url, params: { career: invalid_attributes }
        }.to change(Career, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post careers_url, params: { career: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested career" do
        career = Career.create! valid_attributes
        patch career_url(career), params: { career: new_attributes }
        career.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the career" do
        career = Career.create! valid_attributes
        patch career_url(career), params: { career: new_attributes }
        career.reload
        expect(response).to redirect_to(career_url(career))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        career = Career.create! valid_attributes
        patch career_url(career), params: { career: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested career" do
      career = Career.create! valid_attributes
      expect {
        delete career_url(career)
      }.to change(Career, :count).by(-1)
    end

    it "redirects to the careers list" do
      career = Career.create! valid_attributes
      delete career_url(career)
      expect(response).to redirect_to(careers_url)
    end
  end
end
